### Cadastrar um novo filme
POST https://localhost:5001/api/filme/create
Content-Type: application/json

{
    "Nome" : "Shang Chi",
    "Tipo" : "Ação",
    "Distribuidora": "Walt Disney",
    "Classificacao": 12
}

### Listar todos os filmes
GET https://localhost:5001/api/filme/list
